services:
  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=shareituser
      - POSTGRES_USER=shareituser
      - POSTGRES_DB=shareit

  server:
    build: ./server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090